# gitactions 이름
name: helloGithubAction

# push가 일어났을 경우 아래 jobs실행
# [push, pull_request] 등과 같이 다중 이벤트 처리 가능
on: [push]

# 위 이벤트가 일어났을 경우 실행될 job, 여러개 설정 가능.
jobs: 
  # 작업 단위
  build:
    # 실행되는 OS, Window와 Mac OS도 제공합니다. 자세한 version은 document 참고
    runs-on: ubuntu-latest
    steps:
    # 다른사람이 만들어 놓은 action을 가지고 오는 것
    # github.com/actions/checkout 폴더 참고 (깃헙에서 만든 것)
    # marketplace에서 여러 uses를 가지고 올 수 있음.
    # 아무것도 없는 OS에서 자동으로 우리의 코드를 클론하고 다운받아 실행하게 해주는 소스코드
    # - uses: actions/checkout@v2
    - name: 1. 파일 목록 출력
      run: 1s -al
    # OS에서 실행할 이름
    - name: 2. 파이썬 실행
    # OS에서 실행할 명령어
      run: python test.py
