name: helloGithubAction

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 1. 파일 목록 출력
      run: ls -al
    - name: 2. 파이썬 패키지 확인
      run: pip list
    - name: 3.pip upgrade
      run: python -m pip install --upgrade pip
    - name: 4.package install
      run: pip install -r requirements.txt
    - name: 3. 파이썬 실행
      run: python test.py
